# Generated by Django 5.0.3 on 2024-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otherclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherclient',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
