# Generated by Django 5.0.4 on 2024-10-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_otherclient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'client'), ('Agent', 'Agent'), ('ADMIN', 'admin')], default='', max_length=32),
        ),
    ]
