# Generated by Django 5.0.4 on 2024-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='superuser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customuser',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'client'), ('AGENT', 'Agent'), ('ADMIN', 'admin'), ('superuser', 'superuser')], default='', max_length=32),
        ),
    ]
