# Generated by Django 5.0.4 on 2024-10-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.CharField(default='0.0.0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.CharField(default='0.0.0', max_length=255),
            preserve_default=False,
        ),
    ]
