# Generated by Django 5.0.4 on 2024-10-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('Agent_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='account.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, default=0)),
                ('commande_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('operator', models.CharField(max_length=256)),
                ('transaction_id', models.CharField(max_length=256)),
                ('Prodcut_qte', models.CharField(max_length=256)),
                ('client_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='account.otherclient')),
                ('product_id', models.ManyToManyField(default=0, related_name='commande', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Thums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, default='', upload_to='product/images/')),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
