# Generated by Django 5.0.4 on 2024-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_calender_remove_product_agent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionclient',
            name='end_subscribe',
            field=models.DateField(null=True),
        ),
    ]
